### ISSUE TITLE
Use of $_SERVER["SERVER_NAME"] in SwpmMiscUtils::get_current_page_url()

### ISSUE THREAD

**Issue by utrenkner** [wp-insider/simple-membership#22]
In our WordPress setup, I needed to reverse proxy the request to an internal IP address, e.g. 10.0.0.1.

I use the After Login Redirection Addon. This gets the value of its ``swpm_redirect_to``-Parameter from ``SwpmMiscUtils::get_current_page_url()``, which uses ``$_SERVER["SERVER_NAME"]``, which is 10.0.0.1. Thus, the redirect cannot work as that address is not accessible from the outside.

Could you switch the use of ``$_SERVER["SERVER_NAME"]`` to ``$_SERVER["HTTP_HOST"]`` instead? 

I did a little research on possible downsides to such a switch. Amongst others, I found [this interesting discussion on Stackoverflow](https://stackoverflow.com/questions/1459739/php-serverhttp-host-vs-serverserver-name-am-i-understanding-the-ma).

In essence: ``$_SERVER["HTTP_HOST"]`` solves my issue and I do not see any downsides to make this change in the code permanently.

**Comment by erommel** [comment]
>In essence: $_SERVER["HTTP_HOST"] solves my issue and I do not see any downsides to make this change in the code permanently.

...except that some people might get their things break apart because they were relying on SERVER_NAME rather than HTTP_HOST ;-)

Also, since HTTP_HOST is set by client, it's generally unsafe. https://stackoverflow.com/questions/10350602/how-safe-is-serverhttp-host

The solution I can offer for now is to add a filter which you can hook to and replace SERVER_NAME to HTTP_HOST. Here's an example of the code which you can use for your purposes:

```
add_filter("swpm_get_current_page_url_filter", "get_current_page_url_filter_hook");
function get_current_page_url_filter_hook($urlParts) {
$urlParts['domain']=$_SERVER['HTTP_HOST'];
return $urlParts;
}
```

$urlParts array consist of the following items:
$urlParts['proto'] - protocol. Can be http or https.
$urlParts['domain'] - domain name. Example: example.com
$urlParts['port'] - port. Empty unless you website isn't using some non-standard port (not 80 or 443).
$urlParts['uri'] - requiest URI. Example: /pages/page1 

In order for this to work, you need to install version from dev branch https://github.com/wp-insider/simple-membership/tree/dev

**Comment by utrenkner** [comment]
Thank you so much!

Just don't forget to delete ``wp_die()`` in line 177](https://github.com/wp-insider/simple-membership/blob/dev/simple-membership/classes/class.swpm-utils-misc.php#L177) before you merge your code with master!

**Comment by erommel** [comment]
Thank you for pointing it out. That's dev branch, some unexpected things could be expected there from time to time ;-)
